site_name: Mastering Software Architecture
repo_url: https://github.com/RomeroGabriel/mastering-software-architecture
docs_dir: "documentation"

nav:
  - Home: index.md

theme:
  name: material
  language: en
  logo: images/arch.png
  favicon: images/arch.png
  palette:
      scheme: slate
      primary: black
      accent: yellow
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - markdown-exec

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
