site_name: Mastering Software Architecture
docs_dir: "documentation"

nav:
  - Home: index.md
  - Basic:
    - What's Software Architecture?: basic/whats_software_arc.md
    - Expectations of an Architect: basic/expectations_of_architect.md
    - Architectural Thinking: basic/architectural_thinking.md
  - Modularity: 
    - Definition: modularity/index.md
    - Measuring Modularity: modularity/measuring.md
  - Architecture Characteristics: 
    - Definition: arch_characteristics/arch_characteristics.md
    - Identifying: arch_characteristics/identifying_characteristics.md
    - Measuring and Governing: arch_characteristics/measuring_governing.md

theme:
  name: material
  language: en
  logo: images/arch.png
  favicon: images/arch.png
  palette:
      scheme: slate
      primary: red
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - markdown-exec

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
