site_name: Mastering Software Architecture
docs_dir: "documentation"

nav:
  - Home: index.md
  - Basic:
    - What's Software Architecture?: basic/whats_software_arc.md
    - Expectations of an Architect: basic/expectations_of_architect.md
    - Architectural Thinking: basic/architectural_thinking.md
  - Modularity: 
    - Definition: modularity/index.md
    - Measuring Modularity: modularity/measuring.md
  - Components: components/index.md
  - Architecture Characteristics: 
    - Definition: arch_characteristics/arch_characteristics.md
    - Identifying: arch_characteristics/identifying_characteristics.md
    - Measuring and Governing: arch_characteristics/measuring_governing.md
    - Scope: arch_characteristics/scope.md
  - Architecture Styles:
    - Introduction: arch_styles/index.md
    - Foundations: arch_styles/foundations.md
    - Monolithic vs Distributed Architectures: arch_styles/mono_distributed.md
    - Layered Architecture Style: arch_styles/layered_arch.md
    - Pipeline Architecture Style: arch_styles/pipeline_arch.md
    - Microkernel Architecture Style: arch_styles/microkernel_arch.md
    - Service-Base Architecture Style: arch_styles/service_based_arch.md
    - Event-Driven Architecture Style: arch_styles/event_driven_arch.md
    - Space-Based Architecture Style: arch_styles/space_based_arch.md
    - Orchestration-Driven Service-Oriented Architecture Style: arch_styles/orchestration_arch.md
    - Microservices Architecture Style: arch_styles/microservices.md

theme:
  name: material
  language: en
  logo: images/arch.png
  favicon: images/arch.png
  palette:
      scheme: slate
      primary: red
      accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.instant
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - markdown-exec

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
